"""
DHT handler implementations for the DID:IIoT Verifiable Data Registry.

Two concrete handler classes are provided:

DHTHandler
    Pure-Python implementation backed by the AuthKademlia submodule and
    the dilithium_py library.  Suitable for environments without a Rust
    toolchain.

RustDHTHandler
    Rust-backed implementation using the authkademlia_py PyO3 extension
    (built from auth-kademlia-rs/).  Higher throughput and native Dilithium
    performance.

IMPORTANT — key format incompatibility:
    dilithium_py (Python) and pqcrypto_dilithium (Rust) use different internal
    byte layouts for secret keys.  Keys generated by one handler MUST NOT be
    passed to the other.

Both handlers share the same public interface:
    generate_did_iiot(), get_did_iiot(), get_did_iiot_suffix(),
    get_did_document(), insert_did_document_in_the_DHT(), key_rotation(),
    get_record_from_DHT(), revoke_did_iiot(), start_dht_service(),
    get_vc_from_authoritative_node()
"""

from AuthKademlia.modules import DilithiumKeyManager, KyberKeyManager, Server, DIDSignatureVerifierHandler, SIGNATURE_ALG_LENGTHS
from did_iiot.modules import DIDIndustrialIoT, Service, VerificationMethod, DIDDocument
import utils
import json
from jwt import utils as jwt_utils
import hashlib
from pathlib import Path
import base64
import asyncio
import httpx


class DIDIIoTHandler:
    """Lightweight container for a resolved DID and its associated DID Document.

    Held by both DHT handler classes after a successful generate_did_iiot() call.
    """

    def __init__(self, did: str, did_document: dict, did_dir: str):
        """
        Args:
            did:          Full DID URI, e.g. "did:iiot:<uuid>".
            did_document: DID Document as a Python dict.
            did_dir:      Directory label (informational only, not used at runtime).
        """
        self.did = did
        self.did_document = did_document
        self.did_dir = did_dir

    def get_did_suffix(self) -> str:
        """Return the UUID suffix of the DID (part after the last ':')."""
        return self.did.split(":")[-1]


class DHTHandler:
    """Pure-Python DHT handler backed by AuthKademlia and dilithium_py.

    Manages the full lifecycle of a DID:IIoT identity:
      - keypair generation (Dilithium-2 + Kyber-512)
      - DID Document construction
      - DHT publication, key-rotation, revocation
      - Verifiable Credential retrieval from the Issuer Node

    Key files are persisted to disk under dilith_keys_dir / kyber_keys_dir so
    that the node can be restarted without losing its identity.
    """

    def __init__(self, dilith_keys_dir: str = "proxy_keys_dilithium",
                 kyber_keys_dir: str = "proxy_keys_kyber"):
        """
        Args:
            dilith_keys_dir: Directory for Dilithium-2 key files (.public / .private).
            kyber_keys_dir:  Directory for Kyber-512 key files.
        """
        self.dilith_key_manager = DilithiumKeyManager(dilith_keys_dir)
        self.kyber_key_manager = KyberKeyManager(kyber_keys_dir)
        self.dht_node = Server(signature_verifier_handler=DIDSignatureVerifierHandler())
        self.did_handler = None

    def _ensure_bytes(self, key):
        """No-op for the Python handler; kept for interface symmetry with RustDHTHandler."""
        return key

    def _generate_dilithium_and_kyber_keypairs(self, dilith_key_name: str = "k0",
                                                kyber_key_name: str = "k1"):
        """Generate and persist a fresh Dilithium-2 + Kyber-512 keypair pair."""
        dilith_pk, dilith_sk = self.dilith_key_manager.generate_keypair(2)
        self.dilith_key_manager.store_public_key(dilith_key_name, dilith_pk)
        self.dilith_key_manager.store_private_key(dilith_key_name, dilith_sk)

        kyber_pk, kyber_sk = self.kyber_key_manager.generate_keypair(512)
        self.kyber_key_manager.store_public_key(kyber_key_name, kyber_pk)
        self.kyber_key_manager.store_private_key(kyber_key_name, kyber_sk)

    def _prepare_did_iiot_property(self, did: str, dilith_pk: bytes, kyber_pk: bytes,
                                    id_service: str, service_type: str, service_endpoint: str):
        """Build the VerificationMethod list and Service list for a DID Document.

        Returns:
            Tuple (services: list, verification_methods: list).
        """
        dilithium_public_jwk_jose = utils.get_dilithium_pub_key_for_did_doc(did, dilith_pk, 2)
        kyber_public_jwk_jose = utils.get_kyber_pub_key_for_did_doc(did, kyber_pk, "Kyber-512", "k1")
        dilithium_verification_method = VerificationMethod(f"{did}#k0", type="Authentication",
                                                            public_jwkey=dilithium_public_jwk_jose)
        kyber_verification_method = VerificationMethod(f"{did}#k1", type="KeySessionExchange",
                                                        public_jwkey=kyber_public_jwk_jose)
        main_service = Service(f"{did}#{id_service}", service_type, service_endpoint)
        return [main_service], [dilithium_verification_method, kyber_verification_method]

    def _get_new_keypairs(self):
        """Generate rotation keypairs and return (old_sk, new_sk, new_pk, new_kyber_pk, new_kyber_sk)."""
        self._generate_dilithium_and_kyber_keypairs(dilith_key_name="new-k0", kyber_key_name="new-k1")
        old_sk = self.dilith_key_manager.get_private_key("k0")
        new_sk = self.dilith_key_manager.get_private_key("new-k0")
        new_pk = self.dilith_key_manager.get_public_key("new-k0")
        new_kyber_pk = self.kyber_key_manager.get_public_key("new-k1")
        new_kyber_sk = self.kyber_key_manager.get_private_key("new-k1")
        return old_sk, new_sk, new_pk, new_kyber_pk, new_kyber_sk

    def _load_iss_pub_key(self) -> bytes | None:
        """Load the Issuer Node's raw Dilithium-2 public key from the firmware-embedded file."""
        key_path = Path(__file__).resolve().parent.parent / "issuer_node_public_key.txt"
        try:
            with open(key_path, "rb") as f:
                return f.read()
        except FileNotFoundError:
            print(f"[ERRORE] File not found: {key_path}")
            return None
        except Exception as e:
            print(f"[ERRORE] parsing error: {e}")
            return None

    def generate_did_iiot(self, id_service: str, service_type: str, service_endpoint: str,
                           did_uri: str = None):
        """Generate a new DID:IIoT identity and store it in self.did_handler.

        Args:
            id_service:       Fragment id for the service entry (e.g. "pump-controller").
            service_type:     Service type string (e.g. "Industrial-Pump").
            service_endpoint: Reachable address of the device (e.g. "192.168.1.50:8080").
            did_uri:          Override the auto-generated DID URI (optional).
        """
        self._generate_dilithium_and_kyber_keypairs()
        dilith_pk = self.dilith_key_manager.get_public_key("k0")
        kyber_pk = self.kyber_key_manager.get_public_key("k1")
        did = did_uri if did_uri else DIDIndustrialIoT.generate_did_uri()
        service, verification_methods = self._prepare_did_iiot_property(
            did, dilith_pk, kyber_pk, id_service, service_type, service_endpoint
        )
        did_document = DIDDocument(id=did, verification_methods=verification_methods, service=service)
        self.did_handler = DIDIIoTHandler(did, did_document.get_dict(), "did_document")

    def get_did_iiot(self) -> str | None:
        """Return the full DID URI, or None if no identity has been generated yet."""
        return self.did_handler.did if self.did_handler else None

    def get_did_iiot_suffix(self) -> str | None:
        """Return the UUID suffix of the DID (the DHT lookup key)."""
        return self.did_handler.get_did_suffix() if self.did_handler else None

    def get_did_document(self) -> dict | None:
        """Return the current DID Document dict, or None if not yet generated."""
        return self.did_handler.did_document if self.did_handler else None

    async def insert_did_document_in_the_DHT(self):
        """Sign the DID Document and publish it to the DHT under the DID UUID suffix."""
        if self.did_handler is None:
            return None
        dilith_sk = self._ensure_bytes(self.dilith_key_manager.get_private_key("k0"))
        value = utils.get_signed_did_document_record(self.did_handler.did_document,
                                                      dilith_sk, algorithm="Dilithium-2")
        key = self.did_handler.did.split(":")[-1]
        print(value)
        await self.dht_node.set(key, value)

    async def key_rotation(self):
        """Rotate the Dilithium-2 and Kyber-512 keypairs and update the DHT record.

        Workflow:
            1. Generate new keypairs (stored as "new-k0" / "new-k1").
            2. Build and sign the updated DID Document with the new Dilithium key.
            3. Produce auth_signature = Sign(new_record, old_sk) to prove ownership.
            4. Request a new Verifiable Credential from the Issuer Node.
            5. Push the update to the DHT.
            6. Persist the new keypairs as "k0" / "k1".

        Returns:
            True on success, False or None on failure.
        """
        old_sk, new_sk, new_pk, new_kyber_pk, new_kyber_sk = self._get_new_keypairs()
        new_pk_jwk = utils.get_dilithium_pub_key_for_did_doc(self.did_handler.did, new_pk, 2, "k0")
        dilith_ver_meth = VerificationMethod(f"{self.did_handler.did}#k0", type="Authentication",
                                              public_jwkey=new_pk_jwk)
        new_kyber_pk_jwk = utils.get_kyber_pub_key_for_did_doc(self.did_handler.did, new_kyber_pk, "Kyber-512")
        kyber_ver_meth = VerificationMethod(f"{self.did_handler.did}#k1", type="SessionKeyExchange",
                                             public_jwkey=new_kyber_pk_jwk)

        did_document = self.did_handler.did_document
        did_document['verificationMethod'][0] = dilith_ver_meth.get_dict()
        did_document['verificationMethod'][1] = kyber_ver_meth.get_dict()

        key = self.did_handler.get_did_suffix()
        value = utils.get_signed_did_document_record(did_document, new_sk, algorithm="Dilithium-2")
        auth_signature = self.dilith_key_manager.sign(old_sk, value, 2)

        pub_key_auth_node = self._load_iss_pub_key()
        address = "172.29.0.2:5007"
        url = f"http://{address}/update-vc"
        payload = {
            "auth_signature": base64.urlsafe_b64encode(auth_signature).decode(),
            "key": key,
            "value": base64.urlsafe_b64encode(value).decode()
        }
        print(f"Payload key rotation request: {payload}")
        async with httpx.AsyncClient(timeout=10.0) as async_client:
            try:
                response = await async_client.post(url, json=payload)
            except httpx.RequestError as err:
                print(f"[Log Key Rotation] Http error: {err}")
                return False
            if response.status_code != 200:
                print(f"[Log Key Rotation] Status response: {response.status_code}: {response.text}")
                return False

        new_jwt_vc = response.json()
        new_vc = new_jwt_vc['verifiable-credential']
        vc_array = new_vc.split(".")
        m = f"{vc_array[0]}.{vc_array[1]}".encode('utf-8')
        signature_for_validation = jwt_utils.base64url_decode(vc_array[2].encode())
        vc_is_valid = self.dilith_key_manager.verify_signature(pub_key_auth_node, m,
                                                                signature_for_validation, 2)
        if vc_is_valid:
            with open("vc.json", "w") as vc_file:
                json.dump(new_jwt_vc, vc_file, indent=4)
            print("Success")
        else:
            print("Invalid Verifiable Credential: Invalid Signature")
            return False

        update_success = await self.dht_node.update(key=key, value=value,
                                                     auth_signature=auth_signature)
        if update_success:
            self.dilith_key_manager.store_private_key(key_name="k0", private_key=new_sk)
            self.dilith_key_manager.store_public_key(key_name="k0", public_key=new_pk)
            self.kyber_key_manager.store_private_key(key_name="k1", private_key=new_kyber_sk)
            self.kyber_key_manager.store_public_key(key_name="k1", public_key=new_kyber_pk)
            self.did_handler.did_document = did_document
            return True

    async def get_record_from_DHT(self, key: str) -> bytes | None:
        """Retrieve a raw DHT record by key. Returns bytes or None if not found."""
        return await self.dht_node.get(key)

    async def revoke_did_iiot(self) -> bool:
        """Revoke the current DID by sending an authenticated delete request to the DHT.

        Returns:
            True on success, False if the DHT rejected the operation.
        """
        delete_msg = b"delete-did"
        dilith_priv_key = self.dilith_key_manager.get_private_key("k0")
        auth_signature = self.dilith_key_manager.sign(dilith_priv_key, delete_msg, 2)
        key = self.did_handler.did.split(":")[-1]
        result = await self.dht_node.delete(key, auth_signature, delete_msg)
        if not result:
            print(f"Revoke operation failed! result: {result}")
            return False
        self.did_handler.did = None
        self.did_handler.did_document = None
        return True

    async def start_dht_service(self, port: int):
        """Bind the DHT node to the given UDP port and start listening."""
        await self.dht_node.listen(port)

    async def get_vc_from_authoritative_node(self, modbus_operations: list = None):
        """Retrieve and validate a Verifiable Credential from the Issuer Node.

        Workflow:
            1. Fetch the Issuer Node's DID Document from the DHT (key "status-list").
            2. Extract the HTTP service endpoint.
            3. Poll GET /get-vc with the device DID and hashed public key.
            4. Verify the returned JWT-VC signature with the issuer's public key.
            5. Persist the VC to vc.json on success.

        Args:
            modbus_operations: Optional Modbus operation list to include in the VC request.
        """
        pub_key_auth_node = self._load_iss_pub_key()
        did_auth_node = "did:iiot:status-list"
        result = await self.dht_node.get(key=did_auth_node)
        if not result:
            return None
        raw_did_document = result[12 + 2420:]
        did_document = utils.decode_did_document(raw_did_document)
        address = did_document['service'][0]['serviceEndpoint']
        hashed_pub_key = hashlib.sha256(self.dilith_key_manager.get_public_key('k0')).digest()
        hashed_pub_key_b64 = base64.urlsafe_b64encode(hashed_pub_key).decode()

        async with httpx.AsyncClient(timeout=10.0) as client:
            max_retries = 6
            for attempt in range(max_retries):
                url = f"http://{address}/get-vc"
                params = {
                    "did_sub": self.did_handler.did,
                    "pub_key_hashed_b64": hashed_pub_key_b64,
                    "modbus_operations": modbus_operations or [],
                }
                try:
                    resp = await client.get(url, params=params)
                    if resp.status_code == 200:
                        jwt_vc = resp.json()
                        break
                    print(f"[Log] Response {resp.status_code}: {resp.text}")
                except httpx.RequestError as e:
                    print(f"[Log] Network Error: {e}")
                await asyncio.sleep(5.0)
            else:
                print("[TESTER] Timeout polling /get-vc")
                return None

        vc = jwt_vc['verifiable-credential']
        jwt_array = vc.split(".")
        m = f"{jwt_array[0]}.{jwt_array[1]}".encode('utf-8')
        signature_for_validation = jwt_utils.base64url_decode(jwt_array[2].encode())
        vc_is_valid = self.dilith_key_manager.verify_signature(pub_key_auth_node, m,
                                                                signature_for_validation, 2)
        if vc_is_valid:
            with open("vc.json", "w") as json_file:
                json.dump(jwt_vc, json_file, indent=4)
        else:
            print("Invalid Verifiable Credentials: Invalid Signature")


import authkademlia_py


class RustDHTHandler:
    """Rust-backed DHT handler using the authkademlia_py PyO3 extension.

    Drop-in replacement for DHTHandler with higher throughput.  All signing
    and verification is performed by the Rust implementation.

    PyO3 note:
        Methods on authkademlia_py objects return Vec<u8> as Python lists, not
        bytes.  Use _ensure_bytes() before any slicing or .decode() call.

    Key format note:
        Keys are generated and stored by the Rust DilithiumKeyManager
        (pqcrypto_dilithium crate).  These bytes are incompatible with
        dilithium_py — never pass them to utils.get_signed_did_document_record().
        Use _build_signed_record() instead.
    """

    def __init__(self, dilith_keys_dir: str = "proxy_keys_dilithium",
                 kyber_keys_dir: str = "proxy_keys_kyber"):
        """
        Args:
            dilith_keys_dir: Directory for Dilithium-2 key files.
            kyber_keys_dir:  Directory for Kyber-512 key files.
        """
        self.dilith_key_manager = authkademlia_py.DilithiumKeyManager(dilith_keys_dir, 2)
        self.kyber_key_manager = authkademlia_py.KyberKeyManager(kyber_keys_dir, 512)
        self.dht_node = authkademlia_py.Server(
            ksize=20,
            alpha=3,
            issuer_path="issuer_node_public_key.bin"
        )
        self.did_handler = None

    def _ensure_bytes(self, key) -> bytes:
        """Convert a PyO3 Vec<u8> (returned as Python list) to bytes if needed."""
        if isinstance(key, list):
            return bytes(bytearray(key))
        return key

    def _generate_dilithium_and_kyber_keypairs(self, dilith_key_name: str = "k0",
                                                kyber_key_name: str = "k1"):
        """Generate and persist a fresh Dilithium-2 + Kyber-512 keypair pair."""
        dilith_pk, dilith_sk = self.dilith_key_manager.generate_keypair(2)
        self.dilith_key_manager.store_public_key(dilith_key_name, dilith_pk)
        self.dilith_key_manager.store_private_key(dilith_key_name, dilith_sk)

        kyber_pk, kyber_sk = self.kyber_key_manager.generate_keypair(512)
        self.kyber_key_manager.store_public_key(kyber_key_name, kyber_pk)
        self.kyber_key_manager.store_private_key(kyber_key_name, kyber_sk)

    def _prepare_did_iiot_property(self, did: str, dilith_pk: bytes, kyber_pk: bytes,
                                    id_service: str, service_type: str, service_endpoint: str):
        """Build the VerificationMethod list and Service list for a DID Document.

        Returns:
            Tuple (services: list, verification_methods: list).
        """
        dilithium_public_jwk_jose = utils.get_dilithium_pub_key_for_did_doc(did, dilith_pk, 2)
        kyber_public_jwk_jose = utils.get_kyber_pub_key_for_did_doc(did, kyber_pk, "Kyber-512", "k1")
        dilithium_verification_method = VerificationMethod(f"{did}#k0", type="Authentication",
                                                            public_jwkey=dilithium_public_jwk_jose)
        kyber_verification_method = VerificationMethod(f"{did}#k1", type="KeySessionExchange",
                                                        public_jwkey=kyber_public_jwk_jose)
        main_service = Service(f"{did}#{id_service}", service_type, service_endpoint)
        return [main_service], [dilithium_verification_method, kyber_verification_method]

    def _get_new_keypairs(self):
        """Generate rotation keypairs and return (old_sk, new_sk, new_pk, new_kyber_pk, new_kyber_sk)."""
        self._generate_dilithium_and_kyber_keypairs(dilith_key_name="new-k0", kyber_key_name="new-k1")
        old_sk = self._ensure_bytes(self.dilith_key_manager.get_private_key("k0"))
        new_sk = self._ensure_bytes(self.dilith_key_manager.get_private_key("new-k0"))
        new_pk = self._ensure_bytes(self.dilith_key_manager.get_public_key("new-k0"))
        new_kyber_pk = self._ensure_bytes(self.kyber_key_manager.get_public_key("new-k1"))
        new_kyber_sk = self._ensure_bytes(self.kyber_key_manager.get_private_key("new-k1"))
        return old_sk, new_sk, new_pk, new_kyber_pk, new_kyber_sk

    def _load_iss_pub_key(self) -> bytes | None:
        """Load the Issuer Node's raw Dilithium-2 public key from the firmware-embedded file."""
        key_path = Path(__file__).resolve().parent.parent / "issuer_node_public_key.txt"
        try:
            with open(key_path, "rb") as f:
                return f.read()
        except FileNotFoundError:
            print(f"[ERRORE] File not found: {key_path}")
            return None
        except Exception as e:
            print(f"[ERRORE] parsing error: {e}")
            return None

    def _build_signed_record(self, did_document: dict, sk: bytes,
                              algorithm: str = "Dilithium-2") -> bytes:
        """Assemble a signed DHT record using the Rust Dilithium key manager.

        Must be used instead of utils.get_signed_did_document_record() when the
        secret key was generated by the Rust DilithiumKeyManager — the two libraries
        use incompatible key byte layouts.

        Wire layout:
            algorithm (12 B, null-padded) | Dilithium signature | DID Document JSON

        Args:
            did_document: DID Document dict to sign and store.
            sk:           Rust Dilithium-2 secret key bytes.
            algorithm:    Algorithm tag (default "Dilithium-2").

        Returns:
            Assembled record bytes ready for dht_node.set().
        """
        raw_did_doc = utils.encode_did_document(did_document)
        alg = algorithm.encode('utf-8')[:12].ljust(12, b'\0')
        signature = self._ensure_bytes(
            self.dilith_key_manager.sign(self._ensure_bytes(sk), bytes(raw_did_doc))
        )
        return alg + signature + raw_did_doc

    def generate_did_iiot(self, id_service: str, service_type: str, service_endpoint: str,
                           did_uri: str = None):
        """Generate a new DID:IIoT identity and store it in self.did_handler.

        Args:
            id_service:       Fragment id for the service entry.
            service_type:     Service type string.
            service_endpoint: Reachable address of the device.
            did_uri:          Override the auto-generated DID URI (optional).
        """
        self._generate_dilithium_and_kyber_keypairs()
        dilith_pk = self._ensure_bytes(self.dilith_key_manager.get_public_key("k0"))
        kyber_pk = self._ensure_bytes(self.kyber_key_manager.get_public_key("k1"))
        did = did_uri if did_uri else DIDIndustrialIoT.generate_did_uri()
        service, verification_methods = self._prepare_did_iiot_property(
            did, dilith_pk, kyber_pk, id_service, service_type, service_endpoint
        )
        did_document = DIDDocument(id=did, verification_methods=verification_methods, service=service)
        self.did_handler = DIDIIoTHandler(did, did_document.get_dict(), "did_document")

    def get_did_iiot(self) -> str | None:
        """Return the full DID URI, or None if no identity has been generated yet."""
        return self.did_handler.did if self.did_handler else None

    def get_did_iiot_suffix(self) -> str | None:
        """Return the UUID suffix of the DID (the DHT lookup key)."""
        return self.did_handler.get_did_suffix() if self.did_handler else None

    def get_did_document(self) -> dict | None:
        """Return the current DID Document dict, or None if not yet generated."""
        return self.did_handler.did_document if self.did_handler else None

    async def insert_did_document_in_the_DHT(self):
        """Sign the DID Document with the Rust key manager and publish it to the DHT."""
        if self.did_handler is None:
            return None
        dilith_sk = self._ensure_bytes(self.dilith_key_manager.get_private_key("k0"))
        value = self._build_signed_record(self.did_handler.did_document, dilith_sk)
        key = self.did_handler.did.split(":")[-1]
        print(value)
        await self.dht_node.set(key, value)

    async def key_rotation(self):
        """Rotate keypairs and update the DHT record (Rust key manager variant).

        Same workflow as DHTHandler.key_rotation() but all signing is performed
        by the Rust DilithiumKeyManager via _build_signed_record().

        Returns:
            True on success, False or None on failure.
        """
        old_sk, new_sk, new_pk, new_kyber_pk, new_kyber_sk = self._get_new_keypairs()
        new_pk_jwk = utils.get_dilithium_pub_key_for_did_doc(self.did_handler.did, new_pk, 2, "k0")
        dilith_ver_meth = VerificationMethod(f"{self.did_handler.did}#k0", type="Authentication",
                                              public_jwkey=new_pk_jwk)
        new_kyber_pk_jwk = utils.get_kyber_pub_key_for_did_doc(self.did_handler.did, new_kyber_pk, "Kyber-512")
        kyber_ver_meth = VerificationMethod(f"{self.did_handler.did}#k1", type="SessionKeyExchange",
                                             public_jwkey=new_kyber_pk_jwk)

        did_document = self.did_handler.did_document
        did_document['verificationMethod'][0] = dilith_ver_meth.get_dict()
        did_document['verificationMethod'][1] = kyber_ver_meth.get_dict()

        key = self.did_handler.get_did_suffix()
        value = self._build_signed_record(did_document, new_sk)
        auth_signature = self._ensure_bytes(self.dilith_key_manager.sign(old_sk, bytes(value)))

        pub_key_auth_node = self._load_iss_pub_key()
        address = "172.29.0.2:5007"
        url = f"http://{address}/update-vc"
        payload = {
            "auth_signature": base64.urlsafe_b64encode(auth_signature).decode(),
            "key": key,
            "value": base64.urlsafe_b64encode(value).decode()
        }
        print(f"Payload key rotation request: {payload}")
        async with httpx.AsyncClient(timeout=10.0) as async_client:
            try:
                response = await async_client.post(url, json=payload)
            except httpx.RequestError as err:
                print(f"[Log Key Rotation] Http error: {err}")
                return False
            if response.status_code != 200:
                print(f"[Log Key Rotation] Status response: {response.status_code}: {response.text}")
                return False

        new_jwt_vc = response.json()
        new_vc = new_jwt_vc['verifiable-credential']
        vc_array = new_vc.split(".")
        m = f"{vc_array[0]}.{vc_array[1]}".encode('utf-8')
        signature_for_validation = jwt_utils.base64url_decode(vc_array[2].encode())
        vc_is_valid = self.dilith_key_manager.verify_signature(pub_key_auth_node, m,
                                                                signature_for_validation)
        if vc_is_valid:
            with open("vc.json", "w") as vc_file:
                json.dump(new_jwt_vc, vc_file, indent=4)
            print("Success")
        else:
            print("Invalid Verifiable Credential: Invalid Signature")
            return False

        update_success = await self.dht_node.update(key=key, value=value,
                                                     auth_signature=auth_signature)
        if update_success:
            self.dilith_key_manager.store_private_key(key_name="k0", private_key=new_sk)
            self.dilith_key_manager.store_public_key(key_name="k0", public_key=new_pk)
            self.kyber_key_manager.store_private_key(key_name="k1", private_key=new_kyber_sk)
            self.kyber_key_manager.store_public_key(key_name="k1", public_key=new_kyber_pk)
            self.did_handler.did_document = did_document
            return True

    async def get_record_from_DHT(self, key: str) -> bytes | None:
        """Retrieve a raw DHT record by key.

        Converts the PyO3 list result to bytes before returning so that all
        callers can safely slice and decode without additional conversion.

        Returns:
            bytes or None if the key was not found.
        """
        result = await self.dht_node.get(key)
        return self._ensure_bytes(result) if result is not None else None

    async def revoke_did_iiot(self) -> bool:
        """Revoke the current DID by sending an authenticated delete request to the DHT.

        Returns:
            True on success, False if the DHT rejected the operation.
        """
        delete_msg = b"delete-did"
        dilith_priv_key = self.dilith_key_manager.get_private_key("k0")
        auth_signature = self.dilith_key_manager.sign(dilith_priv_key, delete_msg)
        key = self.did_handler.did.split(":")[-1]
        result = await self.dht_node.delete(key, auth_signature, delete_msg)
        if not result:
            print(f"Revoke operation failed! result: {result}")
            return False
        self.did_handler.did = None
        self.did_handler.did_document = None
        return True

    async def start_dht_service(self, port: int):
        """Bind the Rust DHT node to the given UDP port and start listening on all interfaces."""
        await self.dht_node.listen(port, "0.0.0.0")

    async def get_vc_from_authoritative_node(self, modbus_operations: list = None):
        """Retrieve and validate a Verifiable Credential from the Issuer Node.

        Same workflow as DHTHandler.get_vc_from_authoritative_node() but uses
        the Rust key manager for signature verification and _ensure_bytes() to
        handle PyO3 list→bytes conversion on the DHT result.
        """
        pub_key_auth_node = self._load_iss_pub_key()
        did_auth_node = "did:iiot:status-list"
        result = self._ensure_bytes(await self.dht_node.get(key=did_auth_node))
        if not result:
            return None
        raw_did_document = result[12 + 2420:]
        did_document = utils.decode_did_document(raw_did_document)
        address = did_document['service'][0]['serviceEndpoint']
        hashed_pub_key = hashlib.sha256(self.dilith_key_manager.get_public_key('k0')).digest()
        hashed_pub_key_b64 = base64.urlsafe_b64encode(hashed_pub_key).decode()

        async with httpx.AsyncClient(timeout=10.0) as client:
            max_retries = 6
            for attempt in range(max_retries):
                url = f"http://{address}/get-vc"
                params = {
                    "did_sub": self.did_handler.did,
                    "pub_key_hashed_b64": hashed_pub_key_b64,
                    "modbus_operations": modbus_operations or [],
                }
                try:
                    resp = await client.get(url, params=params)
                    if resp.status_code == 200:
                        jwt_vc = resp.json()
                        break
                    print(f"[Log] Response {resp.status_code}: {resp.text}")
                except httpx.RequestError as e:
                    print(f"[Log] Network Error: {e}")
                await asyncio.sleep(5.0)
            else:
                print("[TESTER] Timeout polling /get-vc")
                return None

        vc = jwt_vc['verifiable-credential']
        jwt_array = vc.split(".")
        m = f"{jwt_array[0]}.{jwt_array[1]}".encode('utf-8')
        signature_for_validation = jwt_utils.base64url_decode(jwt_array[2].encode())
        vc_is_valid = self.dilith_key_manager.verify_signature(pub_key_auth_node, m,
                                                                signature_for_validation)
        if vc_is_valid:
            with open("vc.json", "w") as json_file:
                json.dump(jwt_vc, json_file, indent=4)
        else:
            print("Invalid Verifiable Credentials: Invalid Signature")
